export const DATABASE_CONNECTION = 'DATABASE_CONNECTION';
export const PARTY_MODEL = 'PARTY_MODEL';

export const PARTY_CREATION_LIMITATION = 1;
export const PARTY_MEMBERS_LIMITATION_DEFAULT = 10;
export const PARTY_MEMBERS_LIMITATION_PREMIUM = 25;
